[package]
name = "example-client-rest"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
example-server = { path = "../server", features = ["rest-axum"] }

anyhow = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }