[package]
name = "example-client-jsonrpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
example-server = { path = "../server", features = ["jsonrpsee"] }

anyhow = { workspace = true }
tokio = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client"] }